### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hyossid** [hyossid/crypto-vwap#1]
0.1kb * 50 
1hr 18MB of data - fine to directly save in postgres, think no need message queue for this. 
 
- [ ] Do design, simple 
- [ ] Save websocket received raw data to database 
- [ ] Save on Redis buffer saves all transactions in last 5 mins. key : ticker, value: data 

- [ ] Do calculate VWAP on stream processing, which is purely using websocket data. maybe redis is good idea to keep the most recent VWAP.  
- [ ] Validating using REST
